---
title: "README"
author: "Marcus Beck"
output: 
  html_document:
    code_folding: show
self_contained: yes
---

```{r setup, echo = F}
library(knitr)
opts_chunk$set(warning = F, message = F)
```

## Models {.tabset}

### 30 meters

```{r, fig.height = 9, fig.width = 9}
library(tidyverse)
library(GGally)
library(plotly)
library(MuMIn)

source('R/vif_func.R')

data(crbs)
data(envdat)

# filter data by depth
# scale variables(subtract mean, divide by sd)
tomod <- envdat %>% 
  filter(depth == 30) %>% 
  left_join(crbs, by = 'CTD') %>% 
  select(-depth) %>% 
  gather('var', 'val', -CTD, -abundances, -pa) %>% 
  group_by(var) %>% 
  mutate(
    val = scale(val)
  ) %>% 
  spread(var, val) 

# correlation matrix to plot
toplo <- tomod %>% 
  select(-CTD, -pa) %>% 
  cor(use = 'complete.obs', method = 'spearman') %>% 
  data.frame %>% 
  rownames_to_column('x') %>% 
  gather('y', 'cor', -x) %>% 
  arrange(x, y) %>% 
  mutate(
    x = factor(x), 
    y = factor(y)
  )

# plot
p <- ggplot(toplo, aes(x, y, fill = cor)) +
  geom_tile() + 
  theme(
    axis.title.x = element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  ) + 
  scale_y_discrete(expand = c(0, 0)) + 
  scale_x_discrete(expand = c(0, 0)) + 
  scale_fill_distiller(palette = 'RdYlGn')
ggplotly(p)
```
```{r, fig.height = 6, fig.width = 6}
kpvars <- vif_func(tomod[, -c(1, 2)], trace = F, thresh = 7000)
kpvars

# correlation matrix to plot
toplo <- tomod[, kpvars] %>% 
  cor(use = 'complete.obs', method = 'spearman') %>% 
  data.frame %>% 
  rownames_to_column('x') %>% 
  gather('y', 'cor', -x) %>% 
  arrange(x, y) %>% 
  mutate(
    x = factor(x), 
    y = factor(y)
  )

# plot
p <- ggplot(toplo, aes(x, y, fill = cor)) +
  geom_tile() + 
  theme(
    axis.title.x = element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  ) + 
  scale_y_discrete(expand = c(0, 0)) + 
  scale_x_discrete(expand = c(0, 0)) + 
  scale_fill_distiller(palette = 'RdYlGn')
ggplotly(p)
```
```{r, eval = T, fig.height = 5, fig.width = 8}
# abundance model
formin <- kpvars %>% 
  paste(., collapse = ' + ') %>% 
  paste('log(1 + abundances)', ., sep = ' ~ ') %>% 
  formula

global1 <- glm(formin, data = tomod, na.action = na.pass)

sol1 <- dredge(global1)
head(sol1)
importance(sol1) 

# p/a model
formin <- kpvars %>% 
  paste(., collapse = ' + ') %>% 
  paste('pa', ., sep = ' ~ ') %>% 
  formula

global2 <- glm(formin, data = tomod, na.action = na.pass, family = binomial())

sol2 <- dredge(global2)
head(sol2)

importance(sol2) 

toplo1 <- sol1 %>% 
  importance %>% 
  data.frame(importance = .) %>% 
  rownames_to_column('var') %>% 
  mutate(model = 'abundance')

toplo2<- sol2 %>% 
  importance %>% 
  data.frame(importance = .) %>% 
  rownames_to_column('var') %>% 
  mutate(model = 'p/a')  
toplo <- rbind(toplo1, toplo2)

ggplot(toplo, aes(x = var, y = importance, fill = model)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  coord_flip() + 
  theme_bw() + 
  theme(axis.title.y = element_blank())
                  
```

### 100 meters

```{r, fig.height = 9, fig.width = 9}

# filter data by depth
# scale variables(subtract mean, divide by sd)
tomod <- envdat %>% 
  filter(depth == 100) %>% 
  left_join(crbs, by = 'CTD') %>% 
  select(-depth) %>% 
  gather('var', 'val', -CTD, -abundances, -pa) %>% 
  group_by(var) %>% 
  mutate(
    val = scale(val)
  ) %>% 
  spread(var, val) 

# correlation matrix to plot
toplo <- tomod %>% 
  select(-CTD, -pa) %>% 
  cor(use = 'complete.obs', method = 'spearman') %>% 
  data.frame %>% 
  rownames_to_column('x') %>% 
  gather('y', 'cor', -x) %>% 
  arrange(x, y) %>% 
  mutate(
    x = factor(x), 
    y = factor(y)
  )

# plot
p <- ggplot(toplo, aes(x, y, fill = cor)) +
  geom_tile() + 
  theme(
    axis.title.x = element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  ) + 
  scale_y_discrete(expand = c(0, 0)) + 
  scale_x_discrete(expand = c(0, 0)) + 
  scale_fill_distiller(palette = 'RdYlGn')
ggplotly(p)
```
```{r, fig.height = 6, fig.width = 6}
kpvars <- vif_func(tomod[, -c(1, 2)], trace = F, thresh = 7000)
kpvars

# correlation matrix to plot
toplo <- tomod[, kpvars] %>% 
  cor(use = 'complete.obs', method = 'spearman') %>% 
  data.frame %>% 
  rownames_to_column('x') %>% 
  gather('y', 'cor', -x) %>% 
  arrange(x, y) %>% 
  mutate(
    x = factor(x), 
    y = factor(y)
  )

# plot
p <- ggplot(toplo, aes(x, y, fill = cor)) +
  geom_tile() + 
  theme(
    axis.title.x = element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  ) + 
  scale_y_discrete(expand = c(0, 0)) + 
  scale_x_discrete(expand = c(0, 0)) + 
  scale_fill_distiller(palette = 'RdYlGn')
ggplotly(p)
```
```{r, eval = T, fig.height = 5, fig.width = 8}
# abundance model
formin <- kpvars %>% 
  paste(., collapse = ' + ') %>% 
  paste('log(1 + abundances)', ., sep = ' ~ ') %>% 
  formula

global1 <- glm(formin, data = tomod, na.action = na.pass)

sol1 <- dredge(global1)
head(sol1)
importance(sol1) 

# p/a model
formin <- kpvars %>% 
  paste(., collapse = ' + ') %>% 
  paste('pa', ., sep = ' ~ ') %>% 
  formula

global2 <- glm(formin, data = tomod, na.action = na.pass, family = binomial())

sol2 <- dredge(global2)
head(sol2)

importance(sol2) 

toplo1 <- sol1 %>% 
  importance %>% 
  data.frame(importance = .) %>% 
  rownames_to_column('var') %>% 
  mutate(model = 'abundance')

toplo2<- sol2 %>% 
  importance %>% 
  data.frame(importance = .) %>% 
  rownames_to_column('var') %>% 
  mutate(model = 'p/a')  
toplo <- rbind(toplo1, toplo2)

ggplot(toplo, aes(x = var, y = importance, fill = model)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  coord_flip() + 
  theme_bw() + 
  theme(axis.title.y = element_blank())
                  
```

